INSERT INTO RESTAURANTS(RESTAURANT_ID, RESTAURANT_NAME, STATUS) VALUES (1, 'DUREY', 'A');
INSERT INTO RESTAURANTS(RESTAURANT_ID, RESTAURANT_NAME, STATUS) VALUES (2, 'Cafe', 'A');
INSERT INTO RESTAURANTS(RESTAURANT_ID, RESTAURANT_NAME, STATUS) VALUES (3, 'CHICKFILA', 'A');
INSERT INTO RESTAURANTS(RESTAURANT_ID, RESTAURANT_NAME, STATUS) VALUES (4, 'CHILLIES', 'A');


INSERT INTO  MENU (MENU_ID ,ITEM_NAME ,ITEM_DESC ,PRICE ,STATUS ) VALUES(1, 'COFFEE','COFFEE',10,'A');
INSERT INTO  MENU (MENU_ID ,ITEM_NAME ,ITEM_DESC ,PRICE ,STATUS ) VALUES(2, 'TEA','TEA',10,'A');
INSERT INTO  MENU (MENU_ID ,ITEM_NAME ,ITEM_DESC ,PRICE ,STATUS ) VALUES(3, 'PIZZA','PIZZA',15,'A');

INSERT INTO  TABLES (TABLE_ID ,TABLE_TYPE ,RESTAURANT_ID, TABLE_DESC ,CAPACITY ,STATUS ) VALUES(1, 'TABLE4',1,'4 SEATER',4,'A');
INSERT INTO  TABLES (TABLE_ID ,TABLE_TYPE ,RESTAURANT_ID, TABLE_DESC ,CAPACITY ,STATUS ) VALUES(2, 'TABLE6',1,'6 SEATER',6,'A');
INSERT INTO  TABLES (TABLE_ID ,TABLE_TYPE ,RESTAURANT_ID, TABLE_DESC ,CAPACITY ,STATUS ) VALUES(3, 'TABLE10',1, '10 SEATER',10,'A');


INSERT INTO  TABLES (TABLE_ID ,TABLE_TYPE ,RESTAURANT_ID, TABLE_DESC ,CAPACITY ,STATUS ) VALUES(4, 'TABLE4',2,'4 SEATER',4,'A');
INSERT INTO  TABLES (TABLE_ID ,TABLE_TYPE ,RESTAURANT_ID, TABLE_DESC ,CAPACITY ,STATUS ) VALUES(5, 'TABLE6',2,'6 SEATER',6,'A');
INSERT INTO  TABLES (TABLE_ID ,TABLE_TYPE ,RESTAURANT_ID, TABLE_DESC ,CAPACITY ,STATUS ) VALUES(6, 'TABLE10',2, '10 SEATER',10,'A');

