INSERT INTO  TABLE_RESERVATION (RESTAURANT_ID ,TABLE_ID, USER_ID ,STATUS ,BOOKING_ID ) VALUES( 1,1,1,'A', '1-1-1-1');
INSERT INTO  TABLE_RESERVATION (RESTAURANT_ID ,TABLE_ID, USER_ID ,STATUS ,BOOKING_ID ) VALUES( 2,1,1,'A', '2-2-1-1');
  